### 상품 목록조회

GET https://panda-market-api.vercel.app/products/
Content-Type: application/json

### 상품 상세조회

GET https://panda-market-api.vercel.app/products/1
Content-Type: application/json

### 상품 수정

PATCH https://panda-market-api.vercel.app/products/701
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTE0OCwic2NvcGUiOiJhY2Nlc3MiLCJpYXQiOjE3NDU4MTQ1OTQsImV4cCI6MTc0NTgxNjM5NCwiaXNzIjoic3AtcGFuZGEtbWFya2V0In0.joE-hkvH0-05uXVVqIsWdQYYnU7gyCXEurIKK7QXX-s

{
  "tags": [
    "과자"
  ],
  "price": 45000,
  "description": "감자칩이에용",
  "name": "포테토칩"
}

### 상품 삭제

DELETE https://panda-market-api.vercel.app/products/697
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTE0OCwic2NvcGUiOiJhY2Nlc3MiLCJpYXQiOjE3NDU4MTQ1OTQsImV4cCI6MTc0NTgxNjM5NCwiaXNzIjoic3AtcGFuZGEtbWFya2V0In0.joE-hkvH0-05uXVVqIsWdQYYnU7gyCXEurIKK7QXX-s

### 상품 생성

POST https://panda-market-api.vercel.app/products/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTE0OCwic2NvcGUiOiJhY2Nlc3MiLCJpYXQiOjE3NDU4MTQ1OTQsImV4cCI6MTc0NTgxNjM5NCwiaXNzIjoic3AtcGFuZGEtbWFya2V0In0.joE-hkvH0-05uXVVqIsWdQYYnU7gyCXEurIKK7QXX-s

{
  "images": [
    "https://example.com/..."
  ],
  "tags": [
    "전자제품"
  ],
  "price": 0,
  "description": "string",
  "name": "상품 이름"
}

###